#version: '3.9'

networks:
  app_network:
    driver: bridge

services:
  app:
    container_name: auth-app
    build:
      dockerfile: ./Dockerfile
    image: app
    ports:
      - 8086:8086
    env_file:
      - ./app.env
    networks:
      - app_network
    links:
      - dbPostgresql:dbPostgresql
    depends_on:
      - "dbPostgresql"
    command: ["/app/wait-for-it.sh","dbPostgresql:5432","--","/app/app"]

  dbPostgresql:
    container_name: auth-db
    image: postgres
    restart: always
    env_file:
      - ./app.env
    networks:
      - app_network
    volumes:
      - ./internal/storage/postgresql/init/:/docker-entrypoint-initdb.d/


